package dev.droplet.app.tv

import java.io.ByteArrayOutputStream
import java.io.EOFException
import java.io.IOException
import java.io.InputStream
import java.io.OutputStream

/**
 * The Protocol Buffers wire format, as much of it as the Android TV Remote
 * protocol v2 needs: varints, length-delimited fields and nested messages.
 *
 * Hand-written rather than generated by protoc: the protocol is about twenty
 * small messages, of which droplet writes nine and reads nine, so a codec of
 * this size replaces a Gradle plugin, a protoc download at build time and a
 * runtime library. What it writes is checked byte for byte against what the
 * androidtvremote2 library (the hub's implementation) writes, and what it
 * reads against what that library's protobufs produce (TvProtocolTest).
 * Fields it doesn't know are skipped, as protobuf parsers do, so a TV that
 * adds fields doesn't break it.
 */
internal class ProtoWriter {
    private val out = ByteArrayOutputStream()

    private fun raw(v: Long) {
        var x = v
        while (x and 0x7FL.inv() != 0L) {
            out.write(((x and 0x7F) or 0x80).toInt())
            x = x ushr 7
        }
        out.write(x.toInt())
    }

    private fun tag(field: Int, wire: Int) = raw((field.toLong() shl 3) or wire.toLong())

    /** int32, uint32, enum: negative int32 values take ten bytes, as protobuf sign-extends them. */
    fun int(field: Int, v: Int): ProtoWriter = apply { tag(field, 0); raw(v.toLong()) }

    fun bool(field: Int, v: Boolean): ProtoWriter = apply { tag(field, 0); raw(if (v) 1 else 0) }

    fun bytes(field: Int, v: ByteArray): ProtoWriter = apply {
        tag(field, 2)
        raw(v.size.toLong())
        out.write(v)
    }

    fun string(field: Int, v: String): ProtoWriter = bytes(field, v.toByteArray(Charsets.UTF_8))

    fun message(field: Int, v: ProtoWriter): ProtoWriter = bytes(field, v.toByteArray())

    fun toByteArray(): ByteArray = out.toByteArray()
}

/** Not a well-formed protobuf message. */
class ProtoException(message: String) : IOException(message)

/**
 * One parsed message: every field by number, varints as Long and
 * length-delimited ones as bytes. Fixed-width fields (wire types 1 and 5)
 * aren't used by the protocol and are skipped.
 */
internal class ProtoFields private constructor(private val fields: Map<Int, List<Any>>) {
    fun has(field: Int): Boolean = fields.containsKey(field)

    /** The last value, as protobuf takes for a repeated scalar field; 0 when absent. */
    fun long(field: Int): Long = fields[field]?.lastOrNull { it is Long } as Long? ?: 0L

    fun int(field: Int): Int = long(field).toInt()

    fun bool(field: Int): Boolean = long(field) != 0L

    fun bytes(field: Int): ByteArray? = fields[field]?.lastOrNull { it is ByteArray } as ByteArray?

    fun string(field: Int): String = bytes(field)?.toString(Charsets.UTF_8) ?: ""

    /**
     * A nested message. Several occurrences of one merge, as protobuf
     * specifies; parsing their concatenation is exactly that merge.
     */
    fun message(field: Int): ProtoFields? {
        val parts = fields[field]?.filterIsInstance<ByteArray>() ?: return null
        if (parts.isEmpty()) return null
        val all = ByteArrayOutputStream()
        parts.forEach { all.write(it) }
        return parse(all.toByteArray())
    }

    companion object {
        fun parse(data: ByteArray): ProtoFields {
            val map = LinkedHashMap<Int, MutableList<Any>>()
            var pos = 0
            fun varint(): Long {
                var shift = 0
                var result = 0L
                while (true) {
                    if (pos >= data.size) throw ProtoException("truncated varint")
                    if (shift >= 64) throw ProtoException("varint too long")
                    val b = data[pos++].toInt() and 0xFF
                    result = result or ((b and 0x7F).toLong() shl shift)
                    if (b and 0x80 == 0) return result
                    shift += 7
                }
            }
            fun skip(n: Long) {
                if (n < 0 || n > data.size - pos) throw ProtoException("truncated field")
                pos += n.toInt()
            }
            while (pos < data.size) {
                val key = varint()
                val field = (key ushr 3).toInt()
                if (field <= 0 || key ushr 3 > 0x1FFFFFFF) throw ProtoException("bad field number")
                when ((key and 7).toInt()) {
                    0 -> map.getOrPut(field) { ArrayList(1) }.add(varint())
                    1 -> skip(8)
                    2 -> {
                        val n = varint()
                        if (n < 0 || n > data.size - pos) throw ProtoException("truncated field")
                        map.getOrPut(field) { ArrayList(1) }.add(data.copyOfRange(pos, pos + n.toInt()))
                        pos += n.toInt()
                    }
                    5 -> skip(4)
                    else -> throw ProtoException("unsupported wire type ${key and 7}")
                }
            }
            return ProtoFields(map)
        }
    }
}

/**
 * Framing on both ports: each message is its length as a varint, then the
 * message. [MAX_MESSAGE] bounds what a peer can make droplet allocate; the
 * TV's messages are a few hundred bytes at most.
 */
internal object Frames {
    const val MAX_MESSAGE = 64 * 1024

    fun frame(message: ByteArray): ByteArray {
        val out = ByteArrayOutputStream(message.size + 3)
        var n = message.size
        while (n and 0x7F.inv() != 0) {
            out.write((n and 0x7F) or 0x80)
            n = n ushr 7
        }
        out.write(n)
        out.write(message)
        return out.toByteArray()
    }

    fun write(out: OutputStream, message: ByteArray) {
        out.write(frame(message))
        out.flush()
    }

    /** The next message, or null at a clean end of stream (between messages). */
    fun read(input: InputStream): ByteArray? {
        var size = 0
        var shift = 0
        var first = true
        while (true) {
            val b = input.read()
            if (b < 0) {
                if (first) return null
                throw EOFException("the connection closed inside a message")
            }
            first = false
            size = size or ((b and 0x7F) shl shift)
            if (b and 0x80 == 0) break
            shift += 7
            if (shift > 21) throw ProtoException("message length too long")
        }
        if (size > MAX_MESSAGE) throw ProtoException("message of $size bytes is too big")
        val buf = ByteArray(size)
        var got = 0
        while (got < size) {
            val n = input.read(buf, got, size - got)
            if (n < 0) throw EOFException("the connection closed inside a message")
            got += n
        }
        return buf
    }
}
